config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'profiles/new'
  get 'users/sign_in'
  get 'users/sign_up'
  delete 'users/sign_out'
  get 'about' => 'home#about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    # @profile = current_user.friend.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    # @profile = current_user.friend.build(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @profile = current_user.profile
    redirect_to profiles_path, notice: "This ain't your profile!" if @profile.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
  <%= form.text_field :first_name, class: "form-control", placeholder: "first name", autocomplete: "off"%>
</div>

<div class="field mb-3">
  <%= form.text_field :last_name, class: "form-control", placeholder: "last name", autocomplete: "off"%>
</div>

  <div class="field">
    <%= form.number_field :user_id, id: :profile_user_id, value: current_user.id, type: "hidden" %> 
    </div>

  <div class="actions" >
    <%= form.submit "Save", class: "btn btn-primary m-3 ms-0"  %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="col-11 col-lg-6">
    <div class="card card-form container-sm">
        <h1>Edit Profile</h1>

        <%= render 'form', profile: @profile %>

        <%#= link_to 'Show', @profile %>
        <%= link_to "Don't change it after all...", profiles_path %>
    </div>
</div>

app/views/profiles/index.html.erb
<div class="col-11 col-lg-6">
    <div class="card card-form container-sm"><p id="notice"><%= notice %></p>

    <% @profiles.each do |profile| %>
      <% if profile.user == current_user %>
          <h1><%= current_user.profile.first_name %>'s Profile</h1>
        
          <p>Hi!  I'm <%= profile.first_name %> <%= profile.last_name %>.  Welcome to my profile!</p>
          <%#= profile.user_id %>
         
      
      <% end %>
    <% end %>


<% @profiles.each do |profile| %>
  <% if profile.user == current_user %>
    <div>
      <%#= link_to 'Show', profile, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_profile_path(profile), class: "btn btn-primary" %>
      <%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
  <% end %>
<% end %>

</div>
</div>

app/views/profiles/new.html.erb
<div class="col-11 col-lg-6">
    <div class="card card-form container-sm">
        <h1>Create a Profile</h1>

        <%= render 'form', profile: @profile %>

    </div>
</div>

app/views/profiles/show.html.erb
<div class="col-11 col-lg-6">
    <div class="card card-form container-sm"><p id="notice"><%= notice %></p>

<h1><%= current_user.profile.first_name %>'s Profile</h1>
<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>
<div>
  <%= link_to 'See it!', profiles_path, class: "btn btn-primary"%>
  <%= link_to 'Edit', edit_profile_path(@profile), class: "btn btn-primary" %> 
</div>
</div>
</div>