config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'profiles/new'
  get 'users/sign_in'
  get 'users/sign_up'
  delete 'users/sign_out'
  get 'about' => 'home#about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark footer">
  <div class="container-fluid">
    <a class="navbar-brand">Avocoaster</a>
    <div class=attribution>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
  </div>
  
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-light navbar-expand-lg" style = "background-color: hsl(192, 14%, 93%);">
  <div class="container-fluid">
  <img id = "nav-logo" src='<%= image_path('avocado.png') %>' alt='#' width="35" height= "35">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      <li class="nav-item navbar-nav-left">
          <%= link_to 'Home', root_path, class: 'nav-link'%>
        </li>
       
        <li class="nav-item navbar-nav-left">
          <%= link_to 'About', about_path, class: 'nav-link'%>
        </li>
     
       






                        <div class="nav-item-collapsed">
                          <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                            <%= link_to 'Home', root_path, class: 'nav-link'%>
                            <div class="lil_arrow"></div>
                          </li>
                        </div>
                        
                        <div class="nav-item-collapsed">
                          <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                            <%= link_to 'About', about_path, class: 'nav-link'%>
                            <div class="lil_arrow"></div>
                            </li>
                        </div>

                          <% if user_signed_in? %>

                            <% if current_user.profile.nil? %>
                            
                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Profile', new_profile_path, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>
                            </div>

                            <% else %>

                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Profile', profiles_path, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>
                            </div>
                              
                            <% end %>
                            
                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Edit User', edit_user_registration_path, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>
                            </div>

                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>
                            </div>

                          <% else %>
                          
                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>       
                              
                            </div>

                            <div class="nav-item-collapsed">
                              <li class="nav-item-collapsed nav-item d-flex flex-row align-items-center justify-content-between">
                                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link'%>
                                <div class="lil_arrow"></div>
                              </li>
                            </div>

                        <% end %>

                        </ul>



















      <ul class="navbar-nav navbar-nav-right ms-auto me-3 mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <% if current_user.profile.nil? %>
          <li class="nav-item">
            <%= link_to 'Profile', new_profile_path, class: 'nav-link'%>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Profile', profiles_path, class: 'nav-link'%>
          </li>
          <% end %>
          <li class="nav-item">
          <%= link_to 'Edit User', edit_user_registration_path, class: 'nav-link'%>
          </li>

          <div class="nav-item-dark-container"> 
          <li class="nav-item nav-item-dark">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link py-1'%>
          </li>
          </div>

        <% else %>
        
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'%>
        </li>      

       <div class="nav-item-dark-container">
        <li class="nav-item nav-item-dark">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link py-1'%>
        </li>
        </div>
       
      
      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avocoaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('avocado.png') %>
        
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <br/>
    <div class="container">
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    
    <section id="top" class="d-flex flex-column align-items-center">
      <%= yield %>
    </section>
    <section id="bottom">
    </section>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>